set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE;C:\Program Files (x86)\Windows Kits\10\bin;C:\D\dmd-2.095.0\windows\bin;%PATH%
set DMD_LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\
set VCTOOLSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\
set VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
set WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
set WindowsSdkVersion=10.0.19041.0
set UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
set UCRTVersion=10.0.19041.0

echo out\windows\activedirectory.d >x64\Release\windows.build.rsp
echo out\windows\alljoyn.d >>x64\Release\windows.build.rsp
echo out\windows\antimalware.d >>x64\Release\windows.build.rsp
echo out\windows\applicationinstallationandservicing.d >>x64\Release\windows.build.rsp
echo out\windows\appxpackaging.d >>x64\Release\windows.build.rsp
echo out\windows\audio.d >>x64\Release\windows.build.rsp
echo out\windows\automation.d >>x64\Release\windows.build.rsp
echo out\windows\backgroundintelligenttransferservice.d >>x64\Release\windows.build.rsp
echo out\windows\bluetooth.d >>x64\Release\windows.build.rsp
echo out\windows\cloudfilters.d >>x64\Release\windows.build.rsp
echo out\windows\com.d >>x64\Release\windows.build.rsp
echo out\windows\componentservices.d >>x64\Release\windows.build.rsp
echo out\windows\compression.d >>x64\Release\windows.build.rsp
echo out\windows\controls.d >>x64\Release\windows.build.rsp
echo out\windows\core.d >>x64\Release\windows.build.rsp
echo out\windows\coreaudio.d >>x64\Release\windows.build.rsp
echo out\windows\datadeduplication.d >>x64\Release\windows.build.rsp
echo out\windows\dataexchange.d >>x64\Release\windows.build.rsp
echo out\windows\dbg.d >>x64\Release\windows.build.rsp
echo out\windows\developerlicensing.d >>x64\Release\windows.build.rsp
echo out\windows\deviceaccess.d >>x64\Release\windows.build.rsp
echo out\windows\deviceanddriverinstallation.d >>x64\Release\windows.build.rsp
echo out\windows\dhcp.d >>x64\Release\windows.build.rsp
echo out\windows\direct2d.d >>x64\Release\windows.build.rsp
echo out\windows\direct3d10.d >>x64\Release\windows.build.rsp
echo out\windows\direct3d11.d >>x64\Release\windows.build.rsp
echo out\windows\direct3d12.d >>x64\Release\windows.build.rsp
echo out\windows\direct3d9.d >>x64\Release\windows.build.rsp
echo out\windows\direct3dhlsl.d >>x64\Release\windows.build.rsp
echo out\windows\directcomposition.d >>x64\Release\windows.build.rsp
echo out\windows\directdraw.d >>x64\Release\windows.build.rsp
echo out\windows\directmanipulation.d >>x64\Release\windows.build.rsp
echo out\windows\directml.d >>x64\Release\windows.build.rsp
echo out\windows\directshow.d >>x64\Release\windows.build.rsp
echo out\windows\directwrite.d >>x64\Release\windows.build.rsp
echo out\windows\displaydevices.d >>x64\Release\windows.build.rsp
echo out\windows\distributedfilesystem.d >>x64\Release\windows.build.rsp
echo out\windows\dns.d >>x64\Release\windows.build.rsp
echo out\windows\dwm.d >>x64\Release\windows.build.rsp
echo out\windows\dxgi.d >>x64\Release\windows.build.rsp
echo out\windows\enhancedstorage.d >>x64\Release\windows.build.rsp
echo out\windows\etw.d >>x64\Release\windows.build.rsp
echo out\windows\extensibleauthenticationprotocol.d >>x64\Release\windows.build.rsp
echo out\windows\fax.d >>x64\Release\windows.build.rsp
echo out\windows\fileseverresourcemanager.d >>x64\Release\windows.build.rsp
echo out\windows\filesystem.d >>x64\Release\windows.build.rsp
echo out\windows\gamemode.d >>x64\Release\windows.build.rsp
echo out\windows\gamingdeviceinfo.d >>x64\Release\windows.build.rsp
echo out\windows\gdi.d >>x64\Release\windows.build.rsp
echo out\windows\grouppolicymanagementconsole.d >>x64\Release\windows.build.rsp
echo out\windows\hardwarecounterprofiling.d >>x64\Release\windows.build.rsp
echo out\windows\hid.d >>x64\Release\windows.build.rsp
echo out\windows\hidpi.d >>x64\Release\windows.build.rsp
echo out\windows\htmlhelp.d >>x64\Release\windows.build.rsp
echo out\windows\http.d >>x64\Release\windows.build.rsp
echo out\windows\imapi.d >>x64\Release\windows.build.rsp
echo out\windows\indexserver.d >>x64\Release\windows.build.rsp
echo out\windows\inkinput.d >>x64\Release\windows.build.rsp
echo out\windows\installablefilesystems.d >>x64\Release\windows.build.rsp
echo out\windows\interactioncontext.d >>x64\Release\windows.build.rsp
echo out\windows\interop.d >>x64\Release\windows.build.rsp
echo out\windows\intl.d >>x64\Release\windows.build.rsp
echo out\windows\ipc.d >>x64\Release\windows.build.rsp
echo out\windows\iphelper.d >>x64\Release\windows.build.rsp
echo out\windows\iscsidisc.d >>x64\Release\windows.build.rsp
echo out\windows\js.d >>x64\Release\windows.build.rsp
echo out\windows\kernel.d >>x64\Release\windows.build.rsp
echo out\windows\keyboardandmouseinput.d >>x64\Release\windows.build.rsp
echo out\windows\ldap.d >>x64\Release\windows.build.rsp
echo out\windows\legacywindowsenvironmentfeatures.d >>x64\Release\windows.build.rsp
echo out\windows\location.d >>x64\Release\windows.build.rsp
echo out\windows\machinelearning.d >>x64\Release\windows.build.rsp
echo out\windows\magnification.d >>x64\Release\windows.build.rsp
echo out\windows\mapi.d >>x64\Release\windows.build.rsp
echo out\windows\mbn.d >>x64\Release\windows.build.rsp
echo out\windows\mediafoundation.d >>x64\Release\windows.build.rsp
echo out\windows\mediatransport.d >>x64\Release\windows.build.rsp
echo out\windows\menusandresources.d >>x64\Release\windows.build.rsp
echo out\windows\mib.d >>x64\Release\windows.build.rsp
echo out\windows\mixedreality.d >>x64\Release\windows.build.rsp
echo out\windows\mmc.d >>x64\Release\windows.build.rsp
echo out\windows\mobilebroadband.d >>x64\Release\windows.build.rsp
echo out\windows\mobiledevicemanagementregistration.d >>x64\Release\windows.build.rsp
echo out\windows\monitor.d >>x64\Release\windows.build.rsp
echo out\windows\multicast.d >>x64\Release\windows.build.rsp
echo out\windows\multimedia.d >>x64\Release\windows.build.rsp
echo out\windows\nativewifi.d >>x64\Release\windows.build.rsp
echo out\windows\netbios.d >>x64\Release\windows.build.rsp
echo out\windows\netmanagement.d >>x64\Release\windows.build.rsp
echo out\windows\netshell.d >>x64\Release\windows.build.rsp
echo out\windows\networkdiagnosticsframework.d >>x64\Release\windows.build.rsp
echo out\windows\networkdrivers.d >>x64\Release\windows.build.rsp
echo out\windows\networklistmanager.d >>x64\Release\windows.build.rsp
echo out\windows\networkpolicyserver.d >>x64\Release\windows.build.rsp
echo out\windows\offlinefiles.d >>x64\Release\windows.build.rsp
echo out\windows\opengl.d >>x64\Release\windows.build.rsp
echo out\windows\operationrecorder.d >>x64\Release\windows.build.rsp
echo out\windows\otherdevicetechnologies.d >>x64\Release\windows.build.rsp
echo out\windows\p2p.d >>x64\Release\windows.build.rsp
echo out\windows\packaging.d >>x64\Release\windows.build.rsp
echo out\windows\parentalcontrols.d >>x64\Release\windows.build.rsp
echo out\windows\passwordmanagement.d >>x64\Release\windows.build.rsp
echo out\windows\perf.d >>x64\Release\windows.build.rsp
echo out\windows\performancelogandalerts.d >>x64\Release\windows.build.rsp
echo out\windows\photoacquire.d >>x64\Release\windows.build.rsp
echo out\windows\pointerinput.d >>x64\Release\windows.build.rsp
echo out\windows\policy.d >>x64\Release\windows.build.rsp
echo out\windows\power.d >>x64\Release\windows.build.rsp
echo out\windows\printdocs.d >>x64\Release\windows.build.rsp
echo out\windows\processsnapshotting.d >>x64\Release\windows.build.rsp
echo out\windows\processstatus.d >>x64\Release\windows.build.rsp
echo out\windows\projectedfilesystem.d >>x64\Release\windows.build.rsp
echo out\windows\qualityofservice.d >>x64\Release\windows.build.rsp
echo out\windows\radialinput.d >>x64\Release\windows.build.rsp
echo out\windows\recovery.d >>x64\Release\windows.build.rsp
echo out\windows\remoteassistance.d >>x64\Release\windows.build.rsp
echo out\windows\remotedesktopservices.d >>x64\Release\windows.build.rsp
echo out\windows\remotedifferentialcompression.d >>x64\Release\windows.build.rsp
echo out\windows\restartmanager.d >>x64\Release\windows.build.rsp
echo out\windows\rightsmanagement.d >>x64\Release\windows.build.rsp
echo out\windows\routingandremoteaccessservice.d >>x64\Release\windows.build.rsp
echo out\windows\rpc.d >>x64\Release\windows.build.rsp
echo out\windows\search.d >>x64\Release\windows.build.rsp
echo out\windows\security.d >>x64\Release\windows.build.rsp
echo out\windows\sensors.d >>x64\Release\windows.build.rsp
echo out\windows\serialcontroller.d >>x64\Release\windows.build.rsp
echo out\windows\services.d >>x64\Release\windows.build.rsp
echo out\windows\settingsmanagementinfrastructure.d >>x64\Release\windows.build.rsp
echo out\windows\shell.d >>x64\Release\windows.build.rsp
echo out\windows\snmp.d >>x64\Release\windows.build.rsp
echo out\windows\softwaredevice.d >>x64\Release\windows.build.rsp
echo out\windows\streamingmedia.d >>x64\Release\windows.build.rsp
echo out\windows\structuredstorage.d >>x64\Release\windows.build.rsp
echo out\windows\sync.d >>x64\Release\windows.build.rsp
echo out\windows\systemeventnotificationservice.d >>x64\Release\windows.build.rsp
echo out\windows\systemrestore.d >>x64\Release\windows.build.rsp
echo out\windows\systemservices.d >>x64\Release\windows.build.rsp
echo out\windows\tabletpc.d >>x64\Release\windows.build.rsp
echo out\windows\tapi.d >>x64\Release\windows.build.rsp
echo out\windows\taskscheduler.d >>x64\Release\windows.build.rsp
echo out\windows\textservices.d >>x64\Release\windows.build.rsp
echo out\windows\tilesbadgesnotifications.d >>x64\Release\windows.build.rsp
echo out\windows\titlecallableui.d >>x64\Release\windows.build.rsp
echo out\windows\toolhelp.d >>x64\Release\windows.build.rsp
echo out\windows\touchinput.d >>x64\Release\windows.build.rsp
echo out\windows\tpmbaseservices.d >>x64\Release\windows.build.rsp
echo out\windows\ual.d >>x64\Release\windows.build.rsp
echo out\windows\uianimation.d >>x64\Release\windows.build.rsp
echo out\windows\upnp.d >>x64\Release\windows.build.rsp
echo out\windows\usbdrivers.d >>x64\Release\windows.build.rsp
echo out\windows\useraccesslogging.d >>x64\Release\windows.build.rsp
echo out\windows\virtualstorage.d >>x64\Release\windows.build.rsp
echo out\windows\webdav.d >>x64\Release\windows.build.rsp
echo out\windows\websock.d >>x64\Release\windows.build.rsp
echo out\windows\wia.d >>x64\Release\windows.build.rsp
echo out\windows\windowsaccessibility.d >>x64\Release\windows.build.rsp
echo out\windows\windowsaddressbook.d >>x64\Release\windows.build.rsp
echo out\windows\windowsandmessaging.d >>x64\Release\windows.build.rsp
echo out\windows\windowsbiometricframework.d >>x64\Release\windows.build.rsp
echo out\windows\windowsclustering.d >>x64\Release\windows.build.rsp
echo out\windows\windowscolorsystem.d >>x64\Release\windows.build.rsp
echo out\windows\windowsconnectionmanager.d >>x64\Release\windows.build.rsp
echo out\windows\windowsconnectnow.d >>x64\Release\windows.build.rsp
echo out\windows\windowscontacts.d >>x64\Release\windows.build.rsp
echo out\windows\windowsdeploymentservices.d >>x64\Release\windows.build.rsp
echo out\windows\windowsdesktopsharing.d >>x64\Release\windows.build.rsp
echo out\windows\windowserrorreporting.d >>x64\Release\windows.build.rsp
echo out\windows\windowseventcollector.d >>x64\Release\windows.build.rsp
echo out\windows\windowseventlog.d >>x64\Release\windows.build.rsp
echo out\windows\windowsfiltering.d >>x64\Release\windows.build.rsp
echo out\windows\windowsfirewall.d >>x64\Release\windows.build.rsp
echo out\windows\windowsimagingcomponent.d >>x64\Release\windows.build.rsp
echo out\windows\windowsinformationprotection.d >>x64\Release\windows.build.rsp
echo out\windows\windowsmediadevicemanager.d >>x64\Release\windows.build.rsp
echo out\windows\windowsmediaformat.d >>x64\Release\windows.build.rsp
echo out\windows\windowsmedialibrarysharingservices.d >>x64\Release\windows.build.rsp
echo out\windows\windowsmediaplayer.d >>x64\Release\windows.build.rsp
echo out\windows\windowsnetworking.d >>x64\Release\windows.build.rsp
echo out\windows\windowsnetworkvirtualization.d >>x64\Release\windows.build.rsp
echo out\windows\windowsportabledevices.d >>x64\Release\windows.build.rsp
echo out\windows\windowsprogramming.d >>x64\Release\windows.build.rsp
echo out\windows\windowspropertiessystem.d >>x64\Release\windows.build.rsp
echo out\windows\windowsremotemanagement.d >>x64\Release\windows.build.rsp
echo out\windows\windowsribbon.d >>x64\Release\windows.build.rsp
echo out\windows\windowsserverbackup.d >>x64\Release\windows.build.rsp
echo out\windows\windowssetupandmigration.d >>x64\Release\windows.build.rsp
echo out\windows\windowsstationsanddesktops.d >>x64\Release\windows.build.rsp
echo out\windows\windowssubsystemforlinux.d >>x64\Release\windows.build.rsp
echo out\windows\windowssync.d >>x64\Release\windows.build.rsp
echo out\windows\windowssystemassessmenttool.d >>x64\Release\windows.build.rsp
echo out\windows\windowsupdateagent.d >>x64\Release\windows.build.rsp
echo out\windows\windowswebservices.d >>x64\Release\windows.build.rsp
echo out\windows\wininet.d >>x64\Release\windows.build.rsp
echo out\windows\winrt.d >>x64\Release\windows.build.rsp
echo out\windows\winsock.d >>x64\Release\windows.build.rsp
echo out\windows\wmi.d >>x64\Release\windows.build.rsp
echo out\windows\wpfbitmapeffects.d >>x64\Release\windows.build.rsp
echo out\windows\xamldiagnostics.d >>x64\Release\windows.build.rsp
echo out\windows\xamldiganostics.d >>x64\Release\windows.build.rsp
echo out\windows\xaudio2.d >>x64\Release\windows.build.rsp
echo out\windows\xblidp.d >>x64\Release\windows.build.rsp
echo out\windows\xinput.d >>x64\Release\windows.build.rsp
echo out\windows\xmlhttpextendedrequest.d >>x64\Release\windows.build.rsp
echo out\windows\xps.d >>x64\Release\windows.build.rsp

"C:\Program Files (x86)\VisualD\pipedmd.exe" -deps x64\Release\windows.dep dmd -release -m64 -O -inline -lib -X -Xf"x64\Release\windows.json" -of"x64\Release\windows.lib" @x64\Release\windows.build.rsp
if %errorlevel% neq 0 goto reportError
if not exist "x64\Release\windows.lib" (echo "x64\Release\windows.lib" not created! && goto reportError)

goto noError

:reportError
echo Building x64\Release\windows.lib failed!

:noError
